config/routes.rb
Rails.application.routes.draw do

  resources :recipes

  resources :ingredients

  get 'about' => 'welcome#about'

  root 'welcome#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
   has_many :recipe_ingredients
   has_many :recipes, through: :recipe_ingredient
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :name, :time, :instruction, :serving_size, presence: true
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients
  has_many_attached :images
  belongs_to :category
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def index
    @ingredients = Ingredient.all
  end

  def show
   @ingredient = Ingredient.find(params[:id])
  end

  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)

    if @ingredient.save
      flash[:notice] = "It was saved."
      redirect_to @ingredient
    else
      flash.now[:alert] = "There was an error. Try again."
      render :new
    end
  end

  def edit
    @ingredient = Ingredient.find(params[:id])
  end

  def update
    @ingredient = Ingredient.find(params[:id])
    @ingredient.assign_attributes(ing_params)
    if @ingredient.save
      flash[:notice] = "It was saved."
      redirect_to @ingredient
    else
      flash.now[:alert] = "There was an error. Try again."
      render :edit
    end
  end

  private
  def ing_params
    params.require(:ingredient).permit(:name)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all.with_attached_images
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
    @ingredients = Ingredient.all
    @categories = Category.all.collect{|c| [c.name, c.id] }
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.images.attach(params[:images])
    @recipe.ingredients = Ingredient.where()

    if @recipe.save
      flash[:notice] = "Recipe was saved."
      redirect_to @recipe
    else
      flash.now[:alert] = "There was a problem saving recipe.Try again later."
      render :new
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
    @categories = Category.all.collect{|c| [c.name, c.id] }
  end

  def update
    @recipe = Recipe.find(params[:id])
    @recipe.assign_attributes(recipe_params)

    if @recipe.save
      flash[:notice] = "Recipe was updated."
      redirect_to @recipe
else
  flash.now[:alert] = "There was an error saving the recipe. Try again later."
  render :edit
end
end

def destroy
  @recipe = Recipe.find(params[:id])

  if @recipe.destroy
    flash[:notice] = "\"#{@recipe.name}\" was deleted."
    redirect_to recipes_path
  else
    flash.now[:alert] = "There was an eror deleting the recipe."
    render :show
end
end

  private
   def recipe_params
     params.require(:recipe).permit(:name, :time, :instruction, :serving_size)
   end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/ingredients/edit.html.erb
<h1>Ingredients#edit</h1>
<p>Find me in app/views/ingredients/edit.html.erb</p>

app/views/ingredients/index.html.erb
<h1>Ingredients#index</h1>
<p>Find me in app/views/ingredients/index.html.erb</p>

app/views/ingredients/new.html.erb
<h1>Ingredients#new</h1>
<p>Find me in app/views/ingredients/new.html.erb</p>

app/views/ingredients/show.html.erb
<h1>Ingredients#show</h1>
<p>Find me in app/views/ingredients/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Recipes</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <div class="container">
    <header>
      <h1>Our recipes website</h1>
    </header>
    <main class="content">
      <nav>
        <%= link_to "Home", root_path %>
        <%= link_to "About", about_path %>
      </nav>
      <%= yield %>
    </main>

    <footer>
      <h4>Copyright <%Date.today.year %> OurRecipesWebsite</h4>
    </div>
  </body>
  </html>

app/views/recipes/_form.html.erb
<div class="field">
<%= f.label :category_id %><br />
<%= f.select :category_id, @categories, :include_blank => true %>
</div>

app/views/recipes/edit.html.erb
<h1>Edit Recipe</h1>
<%= form_for @recipe do |f| %>
   <%= f.label :name %>
   <%= f.text_field :name %>

   <%= f.label :time %>
   <%= f.text_field :time %>

   <%= f.label :serving_size %>
   <%= f.text_field :serving_size %>

   <%= f.label :instruction %>
   <%= f.text_area :instruction %>

   <%= f.submit "Save", class: 'btn btn-success'%>
 <% end %>

app/views/recipes/index.html.erb
<h1>All Recipes</h1>
<% @recipes.each do |recipe| %>
  <p><%= link_to recipe.name, recipe %></p>
  <% end %>

app/views/recipes/new.html.erb
<h1> New Recipe </h1>

<%= form_for @recipe do |f| %>
   <%= f.label :name %>
   <%= f.text_field :name %>

   <%= f.label :time %>
   <%= f.text_field :time %>

   <%= f.label :serving_size %>
   <%= f.text_field :serving_size %>

   <%= f.label :instruction %>
   <%= f.text_area :instruction %>

   <%= f.file_field :images, multiple: true %>

   <%= @ingredients %>

   <%= f.submit "Save", class: 'btn btn-success'%>
 <% end %>

app/views/recipes/show.html.erb
<%= @recipe.name %>
<%= @recipe.time %>
<%= @recipe.serving_size %>
<%= @recipe.instruction %>
<%= link_to "Edit", edit_recipe_path(@recipe), class: 'btn btn-success' %>
<%= link_to "Delete", @recipe, method: :delete,class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this recipe?'} %>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>
<%= link_to "Add Recipe", new_recipe_path %>